### ISSUE TITLE
Console errors after updating from 1.0.3 -> 1.0.5

### ISSUE THREAD

**Issue by alexdiliberto** [emberjs/ember-classic-decorator#32] opened 2019-12-05 16:57 UTC
in my app, updating `ember-classic-decorator` from 1.0.3 -> 1.0.5 as the only change throws console errors and breaks the app when running in dev mode

```
vendor.js:113160 Uncaught TypeError: Cannot read property '@ember-data/model/index' of undefined
    at patchDataDecorators (vendor.js:113160)
    at vendor.js:376666
vendor.js:252 Uncaught Error: Could not find module `miragejs` imported from `ember-cli-mirage/response`
    at missingModule (vendor.js:252)
    at findModule (vendor.js:263)
    at Module.findDeps (vendor.js:173)
    at findModule (vendor.js:267)
    at Module.findDeps (vendor.js:173)
    at findModule (vendor.js:267)
    at Module.findDeps (vendor.js:173)
    at findModule (vendor.js:267)
    at requireModule (vendor.js:29)
    at r (vendor.js:181)
    at resolveInitializer (vendor.js:359737)
    at registerInitializers (vendor.js:359754)
    at loadInitializers (vendor.js:359795)
    at Module.callback (neon-tetra.js:1442)
    at Module.exports (vendor.js:111)
    at requireModule (vendor.js:32)
    at neon-tetra.js:46831
```

```
$ ember -v
ember-cli: 3.12.0
node: 10.17.0
os: darwin x64
```

**Comment by alexdiliberto** [comment] 2019-12-05 17:02
Do we need to add the classic decorator to all the mirage adapters/serializer/etc files as well now?

**Comment by pzuraq** [comment] 2020-02-22 17:14
This should be fixed in the latest release, please reopen if it is not.

**Closed by pzuraq** 2020-02-22 17:14 UTC

**Comment by pzuraq** [comment] 2020-02-22 17:18
Ah, also you may need to update `ember-decorators-polyfill`, this bug was caused by interactions between these two addons.
